version: "0.1"
matrix:
  os: [win]
  files: ["golang-hyperexecute-unit-test-sample-repo/Tests/armstrong", "golang-hyperexecute-unit-test-sample-repo/Tests/array", "golang-hyperexecute-unit-test-sample-repo/Tests/case1", "golang-hyperexecute-unit-test-sample-repo/Tests/greet", "golang-hyperexecute-unit-test-sample-repo/Tests/Hello", "golang-hyperexecute-unit-test-sample-repo/Tests/integer", "golang-hyperexecute-unit-test-sample-repo/Tests/multiples", "golang-hyperexecute-unit-test-sample-repo/Tests/oops", "golang-hyperexecute-unit-test-sample-repo/Tests/palindrome", "golang-hyperexecute-unit-test-sample-repo/Tests/repeat"]
runson: ${matrix.os}

pre:
- curl -O https://dl.google.com/go/go1.20.3.windows-amd64.msi

cacheKey: '{{ checksum "go.exe" }}'
cacheDirectories:
- C:\Program Files\Go\bin

mergeArtifacts: true
uploadArtefacts:
- name: Reports
  path:
  - coverage/**

testSuites:
- go test $files -coverpkg=$files -coverprofile=coverage/profile.txt 
